### ISSUE TITLE
Result ThreadRipper 3960X

### ISSUE THREAD

**Issue by ToolsDevler** [nviennot/core-to-core-latency#15]
Hi
Thanks for sharing this cool project!

This is my [output.csv](https://github.com/nviennot/core-to-core-latency/files/9596726/output.csv)

My processor: AMD Ryzen Threadripper 3960X, 3.80GHz, 24 Cores, Zen 2, 3rd Gen, 2019-Q4

Cheers

**Comment by nviennot** [comment]
Super nice, thank you, I've added your results
