### ISSUE TITLE
M1 Air 

### ISSUE THREAD

**Issue by dvtkrlbs** [nviennot/core-to-core-latency#3]
Apperently macos sometimes does not respect affinity settings so i don't know how accurate is it. Probably a asahi linux run would be more accurate
[output.csv](https://github.com/nviennot/core-to-core-latency/files/9595239/output.csv)

**Comment by nviennot** [comment]
Yeah, until we have a way to pin threads to CPUs, it's just going to give us the average between all cores.
What's the chip? M1? M1 Pro? M1 Max?

(About this mac ->  chip)

**Comment by nviennot** [comment]
Okay, regular M1
