### ISSUE TITLE
[Feature Request] Detect and ignore hyperthreading cores

### ISSUE THREAD

**Issue by ashleysommer** [nviennot/core-to-core-latency#8]
The utility needs a way to detect if a `CoreId` is on the same physical core as another `CoreId`, (this indicates a form of hyperthreading or SMT is in use), and filter out those pairs from the benchmark.

You could also build up a table of pairs, and remove all the duplicates, so that on a 8-core CPU, with hyperthreading, only 8 physical cores are included in the benchmark.

**Comment by nviennot** [comment]
That's a good idea. Currently I'm doing the filtering in the python notebook, but it's not ideal.

We could parse /proc/cpuinfo, the information is there

**Comment by ashleysommer** [comment]
I write a little python script a couple of weeks ago that does this, it uses the topology exposed via SysFS, you can check info for each core like this.
`cat /sys/devices/system/cpu/cpu0/topology/thread_siblings_list`

**Comment by CanIGetaPR** [comment]
Makes sense, I ran the test and the 7ns results look like the latency between the hyperthreads in a core.

**Comment by nviennot** [comment]
Ah yes, I don't think I'm going to implement this feature though. If someone wants to give it a shot, I'll merge the feature in

**Comment by nviennot** [comment]
I pushed some changes. There's a CLI flag that allows you to select the core IDs that you wish.
It's more general than just rejecting HTs as it allow to pick sockets, etc.
Let me know what you think
