### ISSUE TITLE
Intel Core i5 10310U 4-core 8-thread (Intel 10th Gen)

### ISSUE THREAD

**Issue by ashleysommer** [nviennot/core-to-core-latency#9]
Testing on my work laptop. Dell Latitude 7410, 2020 model. CPU is Intel Core i5 10310U (10th Gen). 4 cores, 8 threads.

This is on stock clocks (no overclocking), CPU configured in BIOS to 15W TDP, with Base clock 1.7ghz, Boost at 2.2ghz.
Using `NUM_ROUND_TRIPS`=2000 and `NUM_SAMPLES`=1000

_Note, Hyperthreading is turned on, so that makes the 4 core CPU appear as 8 cores in the table._
_This also skews results, with very low latency between threads on the same core._

`core-to-core-latency` utility compiled with  `rustc` stable v1.63.0

Linux OS, Ubuntu 22.04 with Xanmod kernel v5.17

### Power Profile = Performance

> Min  latency: **7.2**ns ±0.1 cores: (7,3)
> Max  latency: **21.6**ns ±0.2 cores: (7,5)
> Mean latency: **18.8**ns
```
,,,,,,,
20.322991249999998,,,,,,,
20.035588249999996,20.2018165,,,,,,
21.16958825,21.369923000000004,21.335075750000005,,,,,
7.300013000000001,20.12066025,19.628703499999997,21.3523555,,,,
21.486786999999996,7.345331250000001,20.029967250000002,21.1629685,19.6607805,,,
19.914945249999995,20.491801999999996,7.382247000000001,21.119740499999995,19.79455025,20.268390750000002,,
20.49829675,21.15840975,21.356683000000004,7.20622025,20.7075525,21.636530999999994,20.944371750000002,
```

**Comment by nviennot** [comment]
Merged, thank you!
